# Generated by Django 5.0.7 on 2024-07-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('txt', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('update', models.DateTimeField()),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_in_one.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_in_one.user')),
            ],
        ),
    ]
