# Generated by Django 5.0.7 on 2024-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
