# Generated by Django 5.0.7 on 2024-07-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0002_alter_post_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('send_date', models.DateTimeField()),
                ('stars', models.IntegerField(verbose_name=5)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_in_one.post')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_in_one.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_in_one.user')),
            ],
        ),
    ]
