# Generated by Django 5.0.7 on 2024-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0005_alter_comment_reply_alter_comment_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
