# Generated by Django 5.0.7 on 2024-07-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0007_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
