# Generated by Django 5.0.7 on 2024-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0009_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
