# Generated by Django 5.0.7 on 2024-07-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0012_alter_save_user_id_alter_like_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='all_in_one.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
