# Generated by Django 5.0.7 on 2024-07-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_in_one', '0014_rename_user_id_save_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
